# application.yaml
spring:
  application:
    name: inventory
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  ai:
    google:
      genai:
        chat:
          model: models/gemini-3.1-flash-lite

frontend:
  url: http://localhost:3000